const goats = [
  {
    id: 'goat1',
    name: 'Billy',
    disposition: 'rude',
    imgUrl: 'https://images2.minutemediacdn.com/image/upload/c_crop,h_843,w_1500,x_0,y_0/f_auto,q_auto,w_1100/v1555172619/shape/mentalfloss/iStock-177369626_0.jpg',
    fullness: 67,
    favPose: 'warrior',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat2',
    name: 'Tim',
    disposition: 'happy',
    imgUrl: 'https://www.telegraph.co.uk/content/dam/pets/2016/08/11/103675361_jack-the-goat-PETS_trans_NvBQzQNjv4BqZgEkZX3M936N5BQK4Va8RWtT0gK_6EfZT336f62EI5U.jpg?imwidth=450',
    fullness: 70,
    favPose: 'childs pose',
    isFainting: false,
    color: 'brown',
  },
  {
    id: 'goat3',
    name: 'Shelia',
    disposition: 'calm',
    imgUrl: 'https://pbs.twimg.com/profile_images/980547001166295041/eBs20xF4.jpg',
    fullness: 50,
    favPose: 'tree',
    isFainting: true,
    color: 'white',
  },
  {
    id: 'goat4',
    name: 'Bob',
    disposition: 'injured',
    imgUrl: 'https://peopledotcom.files.wordpress.com/2018/09/5goats-copy.jpg',
    fullness: 80,
    favPose: 'chair',
    isFainting: true,
    color: 'amber',
  },
  {
    id: 'goat5',
    name: 'Carl',
    disposition: 'angry',
    imgUrl: 'https://images.theconversation.com/files/129851/original/image-20160708-24096-1mslcn7.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=926&fit=clip',
    fullness: 20,
    favPose: 'mountain',
    isFainting: false,
    color: 'black',
  },
];

export default goats;
